package boom


import w.CacheableDoomObject
import java.io.IOException
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * LineSeg, generated by splitting LineDefs
 * using partition lines selected by BSP builder.
 * MAES: this is the ON-DISK structure. The corresponding memory structure,
 * segs_t, has fixed_t members.
 */
class mapseg_v4_t : CacheableDoomObject {
    var v1 = 0
    var v2 = 0
    var angle = 0.toChar()
    var linedef = 0.toChar()
    var side = 0.toChar()
    var offset = 0.toChar()
    @Throws(IOException::class)
    override fun unpack(buf: ByteBuffer) {
        buf.order(ByteOrder.LITTLE_ENDIAN)
        v1 = buf.int
        v2 = buf.int
        angle = buf.char
        linedef = buf.char
        side = buf.char
        offset = buf.char
    }

    companion object {
        fun sizeOf(): Int {
            return 16
        }
    }
}